### ISSUE TITLE
404 error on installation 

### ISSUE THREAD

**Issue by rivera-ernesto** [ebaauw/homebridge-music#21]
`$ sudo npm -g i homebridge-musicAccessories` results in:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/homebridge-musicAccessories - Not found
npm ERR! 404 
npm ERR! 404  'homebridge-musicAccessories@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because 
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2020-04-18T21_24_32_054Z-debug.log
```

The complete logs mentioned above:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   '-g',
1 verbose cli   'i',
1 verbose cli   'homebridge-musicAccessories'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v13.12.0
4 verbose npm-session e1f89299124a7016
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 404 https://registry.npmjs.org/homebridge-musicAccessories 152ms
8 http fetch GET 404 https://registry.npmjs.org/homebridge-musicAccessories 35ms
9 silly fetchPackageMetaData error for homebridge-musicAccessories@latest 404 Not Found - GET https://registry.npmjs.org/homebridge-musicAccessories - Not found
10 timing stage:rollbackFailedOptional Completed in 1ms
11 timing stage:runTopLevelLifecycles Completed in 258ms
12 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/homebridge-musicAccessories - Not found
12 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15
12 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
13 verbose statusCode 404
14 verbose pkgid homebridge-musicAccessories@latest
15 verbose cwd /Users/piggy/Library/Application Support/Plex Media Server/Plug-in Support/Databases
16 verbose Darwin 19.4.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "i" "homebridge-musicAccessories"
18 verbose node v13.12.0
19 verbose npm  v6.14.4
20 error code E404
21 error 404 Not Found - GET https://registry.npmjs.org/homebridge-musicAccessories - Not found
22 error 404
23 error 404 'homebridge-musicAccessories@latest' is not in the npm registry.
24 error 404 Your package name is not valid, because
25 error 404 1. name can no longer contain capital letters
26 error 404 Note that you can also install from a
27 error 404 tarball, folder, http url, or git url.
28 verbose exit [ 1, true ]
```

**Comment by ebaauw** [comment]
I’m sorry, that’s a typo in the README.  It’s `homebridge-music` not `homebridge-musicAccessories`.

**Comment by rivera-ernesto** [comment]
Thanks!
