### ISSUE TITLE
Config Error

### ISSUE THREAD

**Issue by lespatots** [ebaauw/homebridge-music#3]
When I add the Music platform to the config, I get the following error at start up:

[2018-4-28 16:47:39] [mqtt] Number of cached Accessories: 0
[2018-4-28 16:47:39] [mqtt] clientId = homebridge-mqtt_5728e034
[2018-4-28 16:47:39] [mqtt] Connecting..
Error: spawn osascript ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:114:19)
    at Function.Module.runMain (module.js:692:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
Am I missing a depandancy?

**Comment by ebaauw** [comment]
Are you running homebridge on macOS?  For running homebridge automatically, see #2.

**Comment by lespatots** [comment]
No its running on a Pi and I don't run it automatically? OH!, it only runs on a Mac, doesn't quite say that anywhere?

**Comment by ebaauw** [comment]
https://github.com/ebaauw/homebridge-music#prerequisites

homebridge-music uses Applescript (through `osascript`) to talk to iTunes.  That only runs on macOS.

I’ll see if I can check for the OS and issue an error if it’s anything else.

**Comment by lespatots** [comment]
I see its there in the prerequisites. However, its a bit like a software agreement, you give up before the end. Would you consider moving the key line to be the first paragraph!

I guess if I really want to do this I could run a second instance of Homebridge on my Mac?

Sorry to waste your time!

**Comment by ebaauw** [comment]
In v0.1.4
